application: gmhcxw
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?\..*
- ^(.*/)?.+\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*(~|\.(bak|py[co]|csv|sh)|/RCS/.*)

handlers:
- url: /
  static_files: index.html
  secure: always
  upload: index\.html

- url: /gmhcxw.appcache
  static_files: gmhcxw.appcache
  secure: always
  upload: gmhcxw\.appcache

- url: /t
  static_files: text.html
  secure: always
  upload: text\.html

- url: /text.appcache
  static_files: text.appcache
  secure: always
  upload: text\.appcache
