application: computermammalinteractionator
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?\..*
- ^(.*/)?.+\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*(~|\.(bak|py[co]|csv|sh)|/RCS/.*)

handlers:
- url: /
  static_files: index.html
  secure: always
  upload: index\.html

- url: /record
  script: chir.app

- url: /graph
  script: chir.app

- url: /initialize
  script: chir.app

- url: /db.csv
  script: chir.app
